
<template>
<div>
        
<h3>Terms of Use and Privacy Policy www.420Portal.com</h3>

<p>This "Terms of Use and Privacy Policy" (the "Terms") explains the conditions by which you may use the website, located at www.420Portal.com (the "Site") or 420Portal Mobile App (the "App") on Google Play or Apple Store. You should read, understand and agree to all of the Terms prior to using any of the features on the Site or the App or browsing the Site. Downloading, installing or otherwise using (collectively "Use", "Used" or "Using") the Site Or the App constitutes your acceptance of all of these Terms. If you do not agree with the Terms, or any portion of the Terms, leave the Site or the App immediately.</p>

<p>The Site or the App provides online maps, images, videos, coupons, messenger and other resources regarding recreational & medical marijuana by users, dispensaries, collectives & deliveries.(the "Services"). This Site or the App does not sell marijuana and does not encourage in any way the illegal sale of marijuana or any other illegal activities. The information provided is for informational purposes only and is not intended to facilitate any sale or transaction. In these Terms, the owner of the Site & the App is sometimes referred to as "we", "our" or "us".</p>

<p>PLEASE READ THIS DOCUMENT CAREFULLY! IT CONTAINS VERY IMPORTANT INFORMATION ABOUT YOUR RIGHTS AND OBLIGATIONS, AS WELL AS LIMITATIONS AND EXCLUSIONS THAT MAY APPLY TO YOU. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS, DO NOT USE THE SERVICES.</p>

<p>These Terms are effective from the date you first Use the Services and form a binding legal agreement between us and you.</p>

<h5>Accepting the Terms</h5>

<p>1.1 Your use of the Services is subject to the terms of this legal agreement between you and us, the owner of the Site and the App. This document explains the terms of that agreement. Do not use the Services if you do not accept and agree to all of the Terms. </p>

<p>1.2 You may not Use the Services and may not accept the Terms if (a) you are not at least twenty one (21) years of age or older and able to form a binding legal contract with us, or (b) you are a person barred from using the Services under the laws of any country including the country in which you are a resident or from which you Use the Services. THE SERVICES MAY NOT BE USED IN ANY COUNTRY OR LOCATION IN WHICH DOING SO WOULD BE, OR COULD BE DEEMED, A VIOLATION OF ANY LAW, REGULATION, RULE, ORDINANCE, EDICT OR CUSTOM.</p>

<p>1.3 You should print or save a copy of these Terms for your records. The English language versions of the Terms will govern your relationship with us.</p>

<h5>Accepting the Terms</h5>

<p>2.1 Users that are in United States where marijuana use is legal can Use the Services to inform other users about recreational & medical marijuana that are available and the attributes of each, which marijuana dispensaries, collectives, deliveries offers different kinds of marijuana, and other information. There is a map feature that allows users to locate the nearest marijuana dispensary, collective & delivery that sells the type of recreational & medical marijuana they are looking for. To Use many of the Services, you must register. To register, we ask you for certain personal information, such as your email address. </p>
<p>2.2 In the registration process, you may be required to provide information about yourself such as identification, email address or other contact details. You agree that all information provided is done so at your own discretion and that you are not obligated to use the Services or provide any particular piece of information. You agree, however, that any and all information that you do give to us will always be accurate, correct and up to date except that, you may register using an alias. The information you provide will be stored on our servers and used at our discretion in accordance with these Terms. </p>
<p>2.3 We do not necessarily know, and we do not endorse, any particular Dispensary, Collective, Delivery or user. Dispensaries, Collectives & Deliveries who use the Services understand that, by Posting their information through Use of the Services, that information is available to everyone who uses the Services. Dispensaries, Collectives, Deliveries that use the Services understand that, by uploading any image or video through Use of the Services, that information is available to everyone who uses the Services. By uploading information through the Services, or by Using or relying on information that has been uploaded through the Services, you agree that you are doing so at your own risk and that we have no liability for any harm or other damage that may occur as a result your Posting of information or use of information. We have these Terms in place and expect all users to abide by these Terms. However, we ultimately have little to no control over the conduct of the dispensaries, collectives, delivery and users or the truth and accuracy of what those dispensaries, collectives, delivery or users Post including, but not necessarily limited to, the identity of the dispensary, collective, delivery or user and the truth or accuracy of any information given. </p>
<p>2.4 Verifying identity of a Dispensaries, Collectives, Deliveries & Users is extremely difficult and we do not confirm each Dispensary, Collective, Delivery & User's identity. You are responsible for determining the identity of other Dispensaries, Collectives, Deliveries & Users who may contact you or who you may contact by means of the Services. We do not endorse or approve any Dispensary, Collective, Delivery or User who uses or registers for the Services. You are solely responsible for your interactions with other Dispensaries, Collectives, Deliveries or users. We are not responsible for any damage or harm resulting from your interactions with other Dispensaries, Collectives, Deliveries or users. We may, but are not obligated to, monitor interactions between Deliveries, Collectives, Deliveries or users through the Services.</p>

<h5>3. Your Use - Retailers of Recreational or Medical Marijuana Dispensaries, Collectives, Deliveries.</h5>

<p>3.1 Retailers of Recreational or Medical Marijuana Dispensaries, collectives, deliveries agree that the retail store or delivery is in a United State where marijuana use is legal and can Use the Services to inform other users about the different types of recreational & medical marijuana that are available and the attributes of each, which marijuana dispensaries, collectives, deliveries offers different kinds of marijuana, and other information but limited too: media. There is a map feature that allows users to locate the nearest marijuana dispensary, collective & delivery that sells the type of recreational & medical marijuana they are looking for. To Use many of the Services, you must register. To register, we ask you for certain personal information, such as your email address. </p>
<p>3.2 In the registration process, you may be required to provide information about yourself such as identification, email address or other contact details. You agree that all information provided is done so at your own discretion and that you are not obligated to use the Services or provide any particular piece of information. You agree, however, that any and all information that you do give to us will always be accurate, correct and up to date except that, you may register using an alias. The information you provide will be stored on our servers and used at our discretion in accordance with these Terms. </p>
<p>3.3 We do not necessarily know, and we do not endorse, any particular Dispensary, Collective or Delivery. Dispensaries, Collectives & Deliveries who use the Services understand that, by Posting their information through Use of the Services, that information is available to everyone who uses the Services. Dispensaries, Collectives, Delivery that use the Services understand that, by uploading any image or video through Use of the Services, that information is available to everyone who uses the Services. By uploading information through the Services, or by Using or relying on information that has been uploaded through the Services, you agree that you are doing so at your own risk and that we have no liability for any harm or other damage that may occur as a result your Posting of information or use of information. We have these Terms in place and expect all dispensaries, collectives, delivery and users to abide by these Terms. However, we ultimately have little to no control over the conduct of the dispensaries, collectives, delivery and users or the truth and accuracy of what those dispensaries, collectives, delivery or users Post including, but not necessarily limited to, the identity of the dispensary, collective, delivery or user and the truth or accuracy of any information given.</p>
<p>3.4 Verifying identity of a Dispensaries, Collectives, Deliveries & Users is extremely difficult and we do not confirm each Dispensary, Collective, Delivery & User's identity. You are responsible for determining the identity of other Dispensaries, Collectives, Deliveries & Users who may contact you or who you may contact by means of the Services. We do not endorse or approve any Dispensary, Collective, Delivery or User who uses or registers for the Services. You are solely responsible for your interactions with other Dispensaries, Collectives, Deliveries or Users. We are not responsible for any damage or harm resulting from your interactions with other Dispensaries, Collectives, Deliveries or Users. We may, but are not obligated to, monitor interactions between Deliveries, Collectives, Deliveries or Users through the Services.</p>

<h5>4. Provision of the Services</h5>

<p>5.1 You agree to use the Services only for purposes that are permitted by (a) these Terms and (b) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions (including but not limited to any laws regarding the export of data or software to and from the United States or other relevant countries). </p>
<p>5.2 You agree not to access (or attempt to access) any of the Services by any means other than through the Site and, if required, through logging in with your user name and password as intended through your use of the Services. You specifically agree not to access (or attempt to access) any of the Services through any automated means (including but not limited to use of scripts or web crawlers). </p>
<p>5.3 You agree that you will not engage in any activity that interferes with or disrupts the Services (or the servers and networks which may be connected to the Services). </p>
<p>5.4 You agree that you will not reproduce, duplicate, copy, sell, trade or resell the Services or any portion thereof. 5.5 You agree that you are solely responsible for (and that we have no responsibility to you or to any third party for) any breach of your obligations under the Terms and for the consequences (including any loss or damage which we may suffer) of any such breach.</p>

<h5>6. Your passwords and account security</h5>

<p>6.1 You agree and understand that you are responsible for maintaining the confidentiality of passwords associated with any account you use to access the Services. Accordingly, you agree that you will be solely responsible for all activities that occur under your account. You must receive permission from the owner of the account to log in to the Services using another person's account.</p>
<p>6.2 If you become aware of any unauthorized use of your password or of your account, you agree to notify us immediately.</p>
<p>6.3 THE UNAUTHORIZED USE OF YOUR ACCOUNT COULD CAUSE YOU TO INCUR LIABILITY TO US AND/OR THIRD PARTIES. NEITHER US NOR ANY OF OUR OWNERS, EMPLOYEES, AGENTS OR AFFILIATES WILL HAVE ANY LIABILITY TO YOU FOR ANY UNAUTHORIZED POSTING OR OTHER TRANSACTION USING YOUR PASSWORD THAT OCCURS BEFORE YOU HAVE NOTIFIED US OF THE UNAUTHORIZED USE OF YOUR PASSWORD AND WE HAVE HAD A REASONABLE OPPORTUNITY TO ACT ON THAT NOTICE. We may, without notice, suspend or cancel your account at any time if we believe, in our sole discretion, that your password is being used without your authorization or otherwise in a fraudulent manner.</p>

<h5>7. Privacy Policy</h5>

<p>7.1 By submitting personal information, you agree to the Terms including the terms of this Section 7 "Privacy Policy" and you expressly consent to the processing of your personal information according to this Privacy Policy. When you visit the Site or access the Services, you may provide certain types of information including: personal information you knowingly choose to disclose and user information collected by us as you interact with the Site. When you register with us, you provide us with certain personal information. We use that information for our own, internal purposes. One way in which we use the information you provide us is we add your information to our mailing list. This allows us to provide you with information related to the Site such as different promotions that dispensaries, collectives or deliveries may be running or updates to the Services. The Services are not intended for anyone under the age of 18 and we do not knowingly gather personal information about anyone who is under the age of 18. You are able to unsubscribe from our mailing list by following the instructions in the email you receive from us or through your profile page. </p>
<p>7.2 Under certain circumstances, we may collect your browser type and/or IP address and/or mobile location. Our use of this information includes, but is not limited to, gaining insight into the demographics of those utilizing our Services. One of the features of the Site is a location map. Your IP address and/or mobile location may be used to help in the map search results and other location services. </p>
<p>7.3 All information obtained is used for our internal purposes and analysis and is not shared with any third party except for credit card processing as stated in the Terms. </p>
<p>7.4 Whenever you give out personal information when using the Services, that information can be collected and used by people you don't know. While we strive to protect your personal information and privacy, we cannot guarantee the security of any information you disclose online. You make such disclosures at your own risk. </p>
<p>7.5 We may update this Privacy Policy from time to time for any reason. Substantial changes to this Privacy Policy will be posted on this page along with a notice that this Privacy Policy has changed. Once any changes that are made to this Privacy Policy become effective, your continued use of the services after such time will signify your acceptance of the new terms.</p>
<p>7.6 The Site may contain links to other sites. We are not responsible for the privacy practices or the content of any other websites to which the Site links or to which link to the Site. Those websites are owned and operated by third parties and access to and use of those websites is governed by the terms and policies of those websites or resources. You acknowledge and agree that we are not responsible or liable for: (i) the availability or accuracy of such websites; or (ii) the content, advertising, or products on or available from such website. The inclusion of any link, including, but not limited to a link to a recreational or medical marijuana dispensary, collective or dispensary does not imply that we endorse the linked site. You use the websites, links and resources at your own risk. We keep your credit card information on file for the purpose of charging you for fees associated with the Site that you agree to pay such as advertising on the Site. Credit card information used to pay fees associated with the Site may be shared with, and processed by, a third party.</p>
<p>7.7 If you have any questions about this Privacy Policy, please contact us at info@420Portal.com.</p>

<h5>8. Content </h5>

<p>8.1 You understand that all information (such as data files, written text, computer software, music, audio files or other sounds, photographs, videos or other images) which you may have access to as part of, or through your use of, the Services are the sole responsibility of the person from which such content originated. All such information is referred to herein as the "Content" and includes, but is not limited to, Content that The Site, The Apps, Users & Retailers Post. "Post", "Posted" or "Posting" means to upload, post, transmit, share, store, link to or otherwise make available on or through the Services. </p>
<p>8.2 You should be aware that Content presented to you as part of the Services, including but not limited to advertisements on the Site and portions of the Site that we develop, may be protected by intellectual property rights which are owned by those who provide that Content (or by other persons or companies on their behalf). You may not modify, rent, lease, loan, sell, distribute or create derivative works based on Content (either in whole or in part) that you do not own. </p>
<p>8.3 We reserve the right (but shall have no obligation) to pre-screen, review, flag, filter, modify, refuse or remove any or all Content from the Site. For some of the Services, we may not provide tools to filter out Content including explicit sexual content. You understand and agree that there are commercially available services and software to limit access to material that you may find objectionable.</p>
<p>8.4 You understand that by using the Services you may be exposed to Content that you may find offensive, indecent or objectionable and that, in this respect, you use the Site at your own risk.</p>
<p>8.5 You agree that you are solely responsible for (and that we have no responsibility to you or to any third party for) any Content that you Post while using the Services and for the consequences of your actions (including any loss or damage which we may suffer) by doing so.</p>
<p>8.6 When using the Services, you represent and warrant that you will not: Infringe the rights of any other person - Discriminate against, defame, abuse, harass, sexually harass or threaten others - SPAM other members - Knowingly Post fraudulent material, stories or misrepresent yourself in any way - Make any bigoted, hateful, or racially or sexually offensive statements - Advocate illegal activity or discuss illegal activities with the intent to commit them - Post, link to or distribute any material that infringes and/or violates any right of a third party or any law - Post, link to, discuss or distribute any sexually explicit, pornographic, vulgar, obscene, discourteous, or indecent language or images - Post, link to or distribute any software or other materials that contain a virus or other harmful component - Post or distribute material that exploits children - Post Content that is copyrighted and claim it as your own - Post any Content that you do not own or have the right to Post - Register for more than one user account - Impersonate any person or entity, or falsify or otherwise misrepresent yourself or your affiliation with any person or entity.</p>
<p>8.7 We are not responsible for the content or accuracy of any information Posted by Dispensaries, Collectives, Deliveries or users, and shall not be responsible for any transactions made based on such information.</p>
<p>8.8 All illegal activities will be reported to appropriate authorities and will result in termination of your account. </p>
<p>8.9 From time to time, dispensaries, collectives, deliveries or other merchants may advertise through our Site. We do not endorse any particular dispensary, collective, deliveries or merchant. We are not responsible for the accuracy of the content or the redemption of any advertisement. Any issues with any dispensary, collective, delivery or merchant should be resolved between you and the dispensary, collective, delivery or merchant involved; and/or contact the police or call 911 if you are in danger.</p>

<h5>9. Warranty</h5>

<p>9.1 USE OF THE SITE IS AT YOUR OWN RISK. THE SITE, THE SERVICES, AND ALL APPLICATIONS, FEATURES, CONTENT AND MATERIALS MADE AVAILABLE ON, IN CONJUNCTION WITH OR THROUGH THE SITE ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE, OUR OWNERS, EMPLOYEES, SUPPLIERS, LICENSORS AND PARTNERS DISCLAIM ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS. WITHOUT LIMITING THE FOREGOING, WE, OUR OWNERS, EMPLOYEES, SUPPLIERS, LICENSORS AND PARTNERS DO NOT WARRANT THAT THE SERVICES WILL BE AVAILABLE, UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED OR THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SITE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. </p>
<p>9.2 WE ARE NOT RESPONSIBLE OR LIABLE FOR, AND DO NOT APPROVE OR ENDORSE ANY THIRD PARTY (INCLUDING BUT NOT LIMITED TO OTHER USERS) CONTENT, MATERIALS, WEBSITES OR APPLICATIONS MADE AVAILABLE ON OR THROUGH THE SITE (COLLECTIVELY, "THIRD PARTY MATERIALS"). WITHOUT LIMITING THE FOREGOING, WE ARE NOT RESPONSIBLE FOR THE CONTENT, ACCURACY, AVAILABILITY, OFFENSIVENESS, OPINIONS, RELIABILITY, PRIVACY PRACTICES OR OTHER POLICIES APPLICABLE TO SUCH THIRD PARTY MATERIALS, AND WE CANNOT AND DO NOT GUARANTEE THAT THIRD PARTY MATERIALS WILL COMPLY WITH THE RESTRICTIONS, CONDITIONS OR OBLIGATIONS THAT WE REQUIRE. IF YOU DECIDE TO USE OR ACCESS THIRD PARTY MATERIALS, YOU DO SO AT YOUR OWN RISK AND YOU MAY BE REQUIRED TO AGREE TO TERMS OF SERVICE, PRIVACY AND DATA GATHERING PRACTICES AND OTHER POLICIES APPLICABLE TO SUCH THIRD PARTY MATERIALS. PLEASE REVIEW ALL SUCH TERMS AND POLICIES CAREFULLY. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS. </p>
<p>9.3 YOU SPECIFICALLY AGREE THAT IF YOU ARE DISSATISFIED WITH THE SERVICES FOR ANY REASON, YOUR SOLE AND EXCLUSIVE REMEDY IS TO STOP USING THE SERVICES. 9.4 You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country; (ii) you are not listed on any U.S. Government list of prohibited or restricted parties; and (iii) you will comply with all relevant U.N. and EU sanctions and embargoes.</p>

<h5>10. Proprietary Rights</h5>

<p>10.1 You acknowledge and agree that we (or our licensors) own all legal right, title and interest in and to the Site, including any intellectual property rights which subsist in the Site (whether those rights happen to be registered or not, and wherever in the world those rights may exist). You further acknowledge that the Site may contain information which is designated confidential by us and that you shall not disclose such information without our prior written consent. </p>
<p>10.2 Nothing in the Terms gives you a right to use any of our trade names, trademarks, service marks, logos, domain names, and other distinctive brand features. </p>
<p>10.3 You agree that you are responsible for protecting and enforcing any intellectual property right you may have in the Content You Post and that we have no obligation to assist you in any way in protecting or enforcing such rights. </p>
<p>10.4 You agree that you shall not remove, obscure, or alter any proprietary rights notices (including copyright and trademark notices); which may be affixed to or contained within the Site.</p>
<p>10.5 You agree that in using the Site, you will not use any trademark, service mark, trade name or logo of any company or organization that you do not have a right to use and you will not use it in a way that is likely or intended to cause confusion about the owner or authorized user of such marks, names or logos.</p>

<h5>11. License from Us</h5>

<p>11.1 We give you a personal, worldwide, royalty-free, non-assignable and non-exclusive license to use the Site. This license is for the sole purpose of enabling you to use and enjoy the benefit of the Site in the manner permitted by these Terms. </p>
<p>11.2 You may not (and you may not permit anyone else to) copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of any software or any part thereof.</p>

<h5>12. Content that you Post</h5>

<p>12.1 You are solely responsible for all Content You Post. By submitting, Posting or displaying the Content You give us the right to reproduce, adapt, modify, translate, publish, publicly perform, publicly display, sell, distribute and otherwise use the Content in any manner we, in our sole discretion, see fit including, but not limited to, using the Content in advertising of any form and promotional material of any form and kind. This includes, but is not limited to, the right for us to make such Content available to other companies, organizations or individuals.</p>
<p>12.2 You understand and agree that we, at any time and for any reason, may (a) transmit or distribute your Content over various public networks and in various media; and (b) make changes (including adding a watermark or other mark of identification) to your Content as deemed necessary or appropriate by us in our sole discretion.</p>
<p>12.3 You confirm and represent and warrant that you own the Content you Post and have all the rights, power and authority necessary to grant the above. You also represent and warrant that you will not Post any photos or other Content that is fraudulent, defamatory in any way, obscene, vulgar, sexually-oriented, hateful, threatening, or otherwise violative of any laws. We are not responsible, and you agree not to hold us liable, for any comments anyone may Post about you or about Content that you Post. </p>
<p>12.4 As part of the Services, you may send messages to other Dispensaries, Collectives, Deliveries and Users. Any information you provide to other Dispensaries, Collectives, Deliveries and Users is done at your own risk. </p>

<h5>13. LIMITATION OF LIABILITY</h5>

<p>13.1 YOU EXPRESSLY UNDERSTAND AND AGREE THAT WE SHALL NOT BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF YOUR USE, OR INABILITY TO USE, THE SERVICES INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOST PROFITS, LOST SAVINGS, OR FOR ANY DAMAGE RELATED TO THE USE OF OR INABILITY TO USE THE SERVICES EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF ANY SUCH DAMAGES. NO ACTION ARISING OUT OF THIS AGREEMENT, REGARDLESS OF FORM, ARISING OUT OF THIS AGREEMENT MAY BE BROUGHT BY YOU MORE THAN ONE (1) YEAR AFTER THE CAUSE OF ACTION HAS ACCRUED. IN NO EVENT WILL OUR OR OUR OWNERS, EMPLOYEES, LICENSORS OR SUPPLIERS TOTAL AGGREGATE LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, CLAIMS AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OR INABILITY TO USE THE SERVICES, INCLUDING WITHOUT LIMITATION YOUR INTERACTIONS WITH OTHER DISPENSARIES, COLLECTIVES, DELIVERIES, USERS OF THE SITE (WHETHER IN CONTRACT, TORT INCLUDING NEGLIGENCE, WARRANTY OR OTHERWISE) EXCEED THE AMOUNT PAID BY YOU, IF ANY, TO US DURING THE TWELVE MONTHS IMMEDIATELY PRECEDING THE DAY THE ACT OR OMISSION OCCURRED THAT GAVE RISE TO YOUR CLAIM. </p>
<p>13.2 THE LIMITATIONS ON OUR LIABILITY TO YOU SHALL APPLY WHETHER OR NOT WE HAVE BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.</p>

<h5>14. Termination</h5>

<p>14.1 We may terminate and delete your account, delete any Content You have Posted on the Site, and/or prohibit you from using or accessing the Services (or any portion thereof) for any or no reason, and at any time in our sole discretion, with or without notice. Further, we reserve the right to change any aspect or feature of the Site at any time without notice.</p>

<h5>15. Indemnity</h5>

<p>15.1 You agree to indemnify and hold us and our officers, directors, agents and employees, harmless from and against any claim or cause of action brought by a third party as well as any related damages, costs and expenses (including attorneys' fees) ("Claim") arising out of or related to your (a) use of the Services or any of the applications, features, content or materials related thereto; (b) violation of these Terms; (c) violation of the rights of any other person or entity; or (d) breach of the representations, warranties and covenants made by you herein. We reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these Claims.</p>

<h5>16. Venue</h5>

<p>16.1 You agree to submit to the exclusive jurisdiction of the courts located within the City of San Diego, State of California, in the United States of America to resolve any legal matter arising from the Terms. Notwithstanding this, you agree that we shall be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction. These Terms will be interpreted under the laws of the United States of America, State of New York. The terms of the United States Communications Decency Act of 1996, as amended, apply.</p>

<h5>17. General Terms</h5>

<p>17.1 If and to the extent that any provision of these Terms is held illegal, invalid, or unenforceable in whole or in part under applicable law, such provision or such portion thereof shall be ineffective as to the jurisdiction in which it is illegal, invalid, or unenforceable to the extent of its illegality, invalidity, or unenforceability, and, if possible, shall be deemed modified to the extent necessary to conform to applicable law so as to give the maximum effect to the intent of the Parties. The illegality, invalidity, or unenforceability of such provision in that jurisdiction shall not in any way affect the legality, validity, or enforceability of any other provision of these Terms in that or any other jurisdiction. </p>
<p>17.2. Section Headings. The section headings and numbering of these Terms are for convenience of reference only, and shall not define or limit any of the terms or provisions hereof.</p>
<p>17.3 No Waiver. No failure or delay by us in exercising any right, power or privilege hereunder shall operate as a waiver thereof, and no single or partial exercise thereof by us shall preclude any other or further exercise thereof or the exercise of any right, power or privilege hereunder. </p>
<p>17.4 These Terms represent the entire agreement between you and us related to your use of the Services and supersedes all prior understandings, arrangements and representations, whether verbal, written, or presented online.</p>

<h5>Copyright Infringement Notification </h5>
<p>www.420Portal.com RESPECTS THE INTELLECTUAL PROPERTY RIGHTS OF THIRD PARTIES. WE EXPECT OUR USERS TO DO THE SAME. Pursuant to the Digital Millennium Copyright Act of 1998 (DMCA), if you believe that any content appearing anywhere on the Site violates your intellectual property rights, you should contact us immediately and include substantially all of the following information: </p>
<p>I. A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright interest. </p>
<p>II. A description of the copyrighted work that you claim has been infringed, or if there are multiple works, a representative list of the works. Please note that you will be liable for damages (including costs and attorneys' fees) if you materially misrepresent that a file infringes your copyrights.</p>
<p>III. A description of the material that you claim is infringing and information sufficient to establish where it is located on the website. The easiest way to allow us to find the material quickly is to provide the complete URL associated with each file, image or video. </p>
<p>IV. Information that allows us to contact you such as your address, telephone number, and email address;</p>
<p>V. A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and, </p>
<p>VI. A statement by you made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. To process your request, written notice should be sent via email to: info@420Portal.com FALSE CLAIMS - Under Section 512(f) of the Copyright Act, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability for damages. The information provided by you may be forwarded to the person who provided the allegedly infringing content. We do not condone posting, reproduction or distribution of material by anyone other than the owner, copyright holder or the copyright holder's authorized agents. WE MAY REMOVE ANY AND ALL CONTENT AT ANY TIME IN OUR SOLE DISCRETION AND TERMINATE THE ACCOUNTS OF USERS WHO INFRINGE, OR APPEAR TO INFRINGE, THE INTELLECTUAL PROPERTY OR OTHER RIGHTS OF THIRD PARTIES.</p>

</div>
</template>